version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore ./HGV.Divine.sln
build:
  project: /HGV.Divine.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: xm9nZ0BvAZP/W665NGlREwQmdLi0aBBwq2UVagCobe+eAbOPVQ7S+s3ZnKoQgMZB
  skip_symbols: true
  on:
    branch: master