version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: ./src/HGV.Divine.csproj
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore ./HGV.Divine.sln
build:
  project: ./HGV.Divine.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: GvU2An0uWuv8/jga4j3R3Wg2xuRntwQWFw40bzw+UdaVFAKwo3CmllQvXvrHgvko
  skip_symbols: true
  on:
    branch: master